import type { Metadata } from "next";
import { Chivo } from 'next/font/google';
import "./globals.css";

const chivo = Chivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-chivo',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
			<body className={chivo.variable}>
        {children}
      </body>
		</html>
  );
}
